{
 "title": "ELK JVM",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CPU user time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "dub-ixn-elk" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Elasticsearch Heap data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "JVM Elasticsearch" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "dub-ixn-elk" },
     "item": {
      "filter": "JVM Elasticsearch heap capacity"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "JVM Elasticsearch" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "dub-ixn-elk" },
     "item": { "filter": "JVM Elasticsearch heap used" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logstash Heap data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "JVM Logstash" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "dub-ixn-elk" },
     "item": { "filter": "JVM Logstash heap capacity" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "JVM Logstash" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "dub-ixn-elk" },
     "item": { "filter": "JVM Logstash heap used" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}