{
 "title": "Dashboard InnoDB engine",
 "tags": [
  "Production",
  "Zabbix API",
  "MariaDB/MySQL"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Grupo", "query": "*" },
   { "name": "Hosts", "query": "$Grupo.*" }
  ]
 },
 "panels": [
  {
   "title": "Incoming eth0",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "/.*Incoming network traffic on */"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing eth0",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "/.*Outgoing network traffic on*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "description": "Available memory is defined as free+cached+buffers memory (from Zabbix definition)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free SWAP memory %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "System Load (average 1 min)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Free disk space on /",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/ibdata",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/ibdata (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/iblog",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/iblog (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/binlog",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/binlog (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/cache",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/cache (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/data",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/data (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "MySQL memory used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Memory used" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Cache hit ratio" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Slow queries" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Table locks waited",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Table locks waited" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Cache reads from disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "MySQL Aria pagecache read requests"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "InnoDB Buffer pool bytes data/dirty",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "InnoDB" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "InnoDB Buffer pool bytes data" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "InnoDB" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "InnoDB Buffer pool bytes dirty" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "InnoDB data writes/reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "InnoDB" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "InnoDB Data writes" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "InnoDB" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "InnoDB Data reads" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "InnoDB Master thread active/idle loops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "InnoDB" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "InnoDB Master thread active loops"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "InnoDB" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "InnoDB Master thread idle loops"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "InnoDB Row lock time avg",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "InnoDB" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "InnoDB Row lock time avg" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "InnoDB deadlocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "InnoDB" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Innodb Deadlocks" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "InnoDB Non hash searches per sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "InnoDB" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "InnoDB Non hash searches per sec"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}