{
 "title": "Dashboard MariaDB/MySQL server",
 "tags": [
  "Production",
  "Zabbix API",
  "MariaDB/MySQL"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Grupo", "query": "*" },
   { "name": "Hosts", "query": "$Grupo.*" }
  ]
 },
 "panels": [
  {
   "title": "Incoming eth0",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "/.*Incoming network traffic on */"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing eth0",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "/.*Outgoing network traffic on*/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "description": "Available memory is defined as free+cached+buffers memory (from Zabbix definition)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free SWAP memory %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "System Load (average 1 min)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Free disk space on /",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/ibdata",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/ibdata (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/iblog",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/iblog (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/binlog",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/binlog (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/cache",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/cache (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on /db/data",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on /db/data (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "MySQL memory used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Memory used" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Cache hit ratio" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Slow queries" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Table locks waited",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Table locks waited" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Cache reads from disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "MySQL Aria pagecache read requests"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Com select and update - ops/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Com select" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Com update" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MySQL sent and received bytes/sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Bytes sent per second" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "MySQL Bytes received per second"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "30s" ],
       "text": "sum(30s)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Network traffic in eth0" ],
       "text": "setAlias(Network traffic in eth0)"
      }
     ],
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*network traffic*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Connections" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB Aborted connects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Aborted connects" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DB Aborted clients",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "MySQL" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "MySQL Aborted clients" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}