{
 "title": "Dashboard for any Nginx server",
 "tags": [
  "Production",
  "Virtual servers",
  "Zabbix API"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Hosts", "query": "Nginx.*" }
  ]
 },
 "panels": [
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "Availability by ping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "OS" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nginx uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Nginx" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Load (avg 1 min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "description": "Available memory is defined as free+cached+buffers memory (from Zabbix definition)",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free SWAP memory %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free HD space /",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming net traffic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Incoming network traffic on ens18"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing net traffic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Outgoing network traffic on ens18"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nginx active connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Nginx" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nginx Active connections" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nginx accepts/handled/requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Nginx" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nginx Accepts" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Nginx" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nginx handled" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Nginx" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nginx Requests" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Nginx Active connections: reading and writing",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Nginx" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nginx Active connections" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Nginx" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nginx Reading connections" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Nginx" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nginx Writing connections" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Nginx" },
     "group": { "filter": "Nginx" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Nginx waiting connections" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}