{
 "title": "General dashboard for OpenSIPS",
 "tags": [
  "Production",
  "Zabbix API",
  "OpenSIPS"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "cwt-voice-cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Pacemaker_status" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*cwt-voice-sr*/" },
     "item": { "filter": "/.*running resources*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PM resources running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Pacemaker_status" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": {
      "filter": "Pacemaker - running resources on node 1"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free HD /",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "description": "Available memory is defined as free+cached+buffers memory (from Zabbix definition)",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free SWAP memory %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Load (avg 1 min)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming eth0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": {
      "filter": "Incoming network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing eth0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": {
      "filter": "Outgoing network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem total size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": { "filter": "OpenSIPS Shmem Total size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem used size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": { "filter": "OpenSIPS Shmem Real used size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem free size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": { "filter": "OpenSIPS Shmem Free size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PM resources running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Pacemaker_status" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": {
      "filter": "Pacemaker - running resources on node 2"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free HD /",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "description": "Available memory is defined as free+cached+buffers memory (from Zabbix definition)",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free SWAP memory %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Load (avg 1 min)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming eth0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": {
      "filter": "Incoming network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing eth0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": {
      "filter": "Outgoing network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem total size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 2 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": { "filter": "OpenSIPS Shmem Total size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem used size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 2 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": { "filter": "OpenSIPS Shmem Real used size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem free size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 2 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr2.iptel.co" },
     "item": { "filter": "OpenSIPS Shmem Free size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ixn-voice-cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Pacemaker_status" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*ixn-voice-sr*/" },
     "item": { "filter": "/.*running resources*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PM resources running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Pacemaker_status" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr1" },
     "item": {
      "filter": "Pacemaker - running resources on node 1"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free HD /",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "description": "Available memory is defined as free+cached+buffers memory (from Zabbix definition)",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-cwt-voice-sr1" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free SWAP memory %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr1" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Load (avg 1 min)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr1" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming eth0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr1" },
     "item": {
      "filter": "Incoming network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing eth0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr1" },
     "item": {
      "filter": "Outgoing network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem total size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr1" },
     "item": { "filter": "OpenSIPS Shmem Total size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem used size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr1" },
     "item": { "filter": "OpenSIPS Shmem Real used size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem free size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr1" },
     "item": { "filter": "OpenSIPS Shmem Free size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PM resources running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Pacemaker_status" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": {
      "filter": "Pacemaker - running resources on node 2"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free HD  /",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "description": "Available memory is defined as free+cached+buffers memory (from Zabbix definition)",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free SWAP memory %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Load (avg 1 min)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": {
      "filter": "Processor load (1 min average per core)"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Incoming eth0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 6 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": {
      "filter": "Incoming network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Outgoing eth0",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 6 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": {
      "filter": "Outgoing network traffic on eth0"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem free size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": { "filter": "OpenSIPS Shmem Free size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem used size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": { "filter": "OpenSIPS Shmem Used size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Shmem free size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Opensips Shmem" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "dub-ixn-voice-sr2" },
     "item": { "filter": "OpenSIPS Shmem Free size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOTAL Failed and Processed dialogs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Dialog" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Failed dialogs" ],
       "text": "setAlias(Failed dialogs)"
      }
     ],
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Dialog Failed dialogs" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Opensips Dialog" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Processed dialogs" ],
       "text": "setAlias(Processed dialogs)"
      }
     ],
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": {
      "filter": "OpenSIPS Dialog Processed dialogs"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOTAL Active,  Early and Expired dialogs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Dialog" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Active dialogs" ],
       "text": "setAlias(Active dialogs)"
      }
     ],
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Dialog Active dialogs" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Opensips Dialog" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Expired dialogs" ],
       "text": "setAlias(Expired dialogs)"
      }
     ],
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": {
      "filter": "OpenSIPS Dialog Expired dialogs"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Opensips Dialog" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Early dialogs" ],
       "text": "setAlias(Early dialogs)"
      }
     ],
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Dialog Early dialogs" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SI 1xx replies",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Sl" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Sl 1xx replies" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SI 2xx replies",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Sl" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Sl 2xx replies" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SI 3xx replies",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Sl" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Sl 3xx replies" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SI 4xx replies",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Sl" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Sl 4xx replies" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SI 5xx replies",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Sl" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Sl 5xx replies" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SI 6xx replies",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Sl" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Sl 6xx replies" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Rejected registrations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Registrar" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": {
      "filter": "OpenSIPS Registrar Rejected registrations"
     },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TM 2xx transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Tm" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Tm 2xx transactions" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TM 3xx transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Tm" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Tm 3xx transactions" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TM 4xx transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Tm" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Tm 4xx transactions" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TM 5xx transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Tm" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Tm 5xx transactions" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TM 6xx transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Opensips Tm" },
     "group": { "filter": "OpenSIPS" },
     "host": { "filter": "/.*sr*/" },
     "item": { "filter": "OpenSIPS Tm 6xx transactions" },
     "options": {
      "showDisabledItems": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}